### ISSUE TITLE
No method matching autobuild

### ISSUE THREAD

**Issue by dpo** [JuliaPackaging/BinaryBuilder.jl#501] opened 2019-11-18 02:54 UTC
I'm reviving an old `build_tarballs.jl` of mine and *finally* managed to build for macOS. I wonder if anything changed since I first generated that script because TravisCI now tells me
```julia
ERROR: LoadError: MethodError: no method matching autobuild(::String, ::String, ::VersionNumber, ::Array{Any,1}, ::String, ::Array{Platform,1}, ::typeof(products), ::Array{Any,1}; verbose=false, debug=false, meta_json_stream=nothing)
```
https://travis-ci.org/JuliaSmoothOptimizers/ThinASLBuilder/builds/613291589#L306

The script works well locally (on macOS) and generates all artefacts with BinaryBuilder 0.1.4. Here's a link to the script: https://github.com/JuliaSmoothOptimizers/ThinASLBuilder/blob/master/build_tarballs.jl

Thanks.

**Comment by giordano** [comment] 2019-11-18 05:52
This is a duplicate of #492. Please, contribute the builder to [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil/)

**Closed by giordano** 2019-11-18 05:52 UTC

**Comment by dpo** [comment] 2019-11-18 18:07
Thanks. Didn't know about Yggdrasil.

**Comment by giordano** [comment] 2019-11-18 18:09
It's a recent treasure :slightly_smiling_face:

**Comment by dpo** [comment] 2019-11-22 03:36
It's wonderful indeed, thank you for all that hard work!!!

Just to be sure: if we're still using Julia 1.2, we can't use JLLs and must continue with the "old ways" of BinaryBuilder, right?

And if that's correct, what's the preferred way to build macOS binaries on TravisCI without breaking the Apple SDK licensing terms? Is it even possible?

**Comment by giordano** [comment] 2019-11-23 16:26
> And if that's correct, what's the preferred way to build macOS binaries on TravisCI without breaking the Apple SDK licensing terms? Is it even possible?

This is detailed in the FAQ: https://juliapackaging.github.io/BinaryBuilder.jl/latest/FAQ/#What-is-this-I-hear-about-the-macOS-SDK-license-agreement?-1
