### ISSUE TITLE
Provide a complete code block at the end of the build with hashes

### ISSUE THREAD

**Issue by davidanthoff** [JuliaPackaging/BinaryBuilder.jl#48] opened 2017-11-20 00:46 UTC
It would be nice if at the end of the build script it would provide code that looks like [this](https://github.com/bicycle1885/Snappy.jl/pull/13/files#diff-ed74277d7f2e98f12cf51e6b8be90705R12) so that one can just copy paste it into the corresponding ``build.jl`` script.

**Comment by staticfloat** [comment] 2017-11-21 19:05
Duplicate of https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/39 :)

**Closed by staticfloat** 2017-11-21 19:05 UTC
