### ISSUE TITLE
UndefVarError: gh_username not defined

### ISSUE THREAD

**Issue by ig-or** [JuliaPackaging/BinaryBuilder.jl#943] opened 2020-10-13 04:20 UTC
Hello! 
Everything stopped with the error at step 7:
```
# Step 7: Deployment

How should we deploy this build recipe?
 > Prepare a pull request against the community buildtree, Yggdrasil
   Write to a local file
   Print to stdout

Would you like to actually open the pull request or just prepare it?
 > Go ahead, open it
   No, just prepare it and let me look at it first

Creating a github access token
To continue, we need to create a GitHub access token, so that we can do
things like fork Yggdrasil and create pull requests against it.  To create
an access token, you will be asked to enter your GitHub credentials:

GitHub username:
> ig-or

GitHub password:
> 

┌ Warning: a SecretBuffer was `shred!`ed by the GC; use `shred!` manually after use to minimize exposure.
└ @ Base secretbuffer.jl:169
Successfully obtained GitHub authorization token!
This token will be used for the rest of this BB session, however if you
wish to use this token permanently, you may set it in your environment
as via the following line in your~/.julia/config/startup.jlfile:

    ENV["GITHUB_TOKEN"] = "xxx"
This token is sensitive, so only do this in a computing environment you trust.

[ Info: Checking temporary Yggdrasil out to /tmp/jl_W7Wpvb
[ Info: Generating Q/qwt/build_tarballs.jl
[ Info: Committing and pushing to ig-or/Yggdrasil#wizard/qwt-v6.0.0_4fe4ad66...
UndefVarError: gh_username not defined
Stacktrace:
 [1] (::BinaryBuilder.Wizard.var"#129#133"{Bool,String,VersionNumber,Array{BinaryBuilderBase.PatchSource,1},String,GitHub.OAuth2,GitHub.Repo})(::String) at /home/igor/.julia/packages/BinaryBuilder/OMMHj/src/wizard/deploy.jl:177
 [2] mktempdir(::BinaryBuilder.Wizard.var"#129#133"{Bool,String,VersionNumber,Array{BinaryBuilderBase.PatchSource,1},String,GitHub.OAuth2,GitHub.Repo}, ::String; prefix::String) at ./file.jl:682
 [3] mktempdir(::Function, ::String) at ./file.jl:680 (repeats 2 times)
 [4] yggdrasil_deploy(::String, ::VersionNumber, ::Array{BinaryBuilderBase.PatchSource,1}, ::String; open_pr::Bool, branch_name::Nothing) at /home/igor/.julia/packages/BinaryBuilder/OMMHj/src/wizard/deploy.jl:141
 [5] yggdrasil_deploy(::BinaryBuilder.Wizard.WizardState, ::Bool) at /home/igor/.julia/packages/BinaryBuilder/OMMHj/src/wizard/deploy.jl:127
 [6] _deploy(::BinaryBuilder.Wizard.WizardState) at /home/igor/.julia/packages/BinaryBuilder/OMMHj/src/wizard/deploy.jl:235
 [7] step7(::BinaryBuilder.Wizard.WizardState) at /home/igor/.julia/packages/BinaryBuilder/OMMHj/src/wizard/deploy.jl:267
 [8] run_wizard(::Nothing) at /home/igor/.julia/packages/BinaryBuilder/OMMHj/src/Wizard.jl:116
 [9] run_wizard() at /home/igor/.julia/packages/BinaryBuilder/OMMHj/src/Wizard.jl:86
 [10] top-level scope at REPL[2]:1
 [11] eval(::Module, ::Any) at ./boot.jl:331
 [12] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:134
 [13] repl_backend_loop(::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:195
 [14] start_repl_backend(::REPL.REPLBackend, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:180
 [15] run_repl(::REPL.AbstractREPL, ::Any; backend_on_current_task::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:292
 [16] run_repl(::REPL.AbstractREPL, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:288
 [17] (::Base.var"#807#809"{Bool,Bool,Bool,Bool})(::Module) at ./client.jl:399
 [18] #invokelatest#1 at ./essentials.jl:710 [inlined]
 [19] invokelatest at ./essentials.jl:709 [inlined]
 [20] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:383
 [21] exec_options(::Base.JLOptions) at ./client.jl:313
 [22] _start() at ./client.jl:506

WizardState [step7]

julia> 
```

**Comment by giordano** [comment] 2020-10-13 09:14
@ig-or I believe this is a duplicate of #939.  For the time being I think the easiest thing to do is to choose the option "Write to a local file" and manually open a new pull request from there.

The method used in the latest stable version of BinaryBuilder will not work anyway in a couple of weeks because of some changes in GitHub authentication.

Note: I ***strongly*** suggest you to delete the personal access token created in this session.

**Comment by ig-or** [comment] 2020-10-13 18:00
Thanks for your reply!
will do a pull request

**Closed** 2020-11-05 19:41 UTC
Labels: wizard
