### ISSUE TITLE
wizard failed to download GCCBootstrap artifact

### ISSUE THREAD

**Issue by fonsp** [JuliaPackaging/BinaryBuilder.jl#1335] opened 2024-07-01 14:01 UTC
(Total beginner here) I tried to go through the wizard but it failed in a step that downloads a GCC artifact. Here is the complete output of my run:

```
➜  ~ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.10.3 (2024-04-30)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.10) pkg> activate --temp
  Activating new project at `/var/folders/v_/fhpj9jn151d4p9c2fdw2gv780000gn/T/jl_3EAYtE`

(jl_3EAYtE) pkg> add BinaryBuilder
   Resolving package versions...
   Installed Zstd_jll ───────────────── v1.5.6+0
   Installed SodiumSeal ─────────────── v0.1.1
   Installed JSON3 ──────────────────── v1.14.0
   Installed JLD2 ───────────────────── v0.4.48
   Installed Attr_jll ───────────────── v2.5.2+0
   Installed Mocking ────────────────── v0.7.8
   Installed Bzip2_jll ──────────────── v1.0.8+1
   Installed AutoHashEquals ─────────── v0.2.0
   Installed RegistryTools ──────────── v2.3.0
   Installed BinaryBuilderBase ──────── v1.30.0
   Installed ZMQ ────────────────────── v1.2.6
   Installed BinaryBuilder ──────────── v0.5.8
   Installed InlineStrings ──────────── v1.4.1
   Installed XZ_jll ─────────────────── v5.4.6+0
   Installed StructIO ───────────────── v0.3.0
   Installed TZJData ────────────────── v1.2.0+2024a
   Installed TimeToLive ─────────────── v0.3.0
   Installed TimeZones ──────────────── v1.17.0
   Installed GitForge ───────────────── v0.4.2
   Installed Tar_jll ────────────────── v1.35.0+0
   Installed pigz_jll ───────────────── v2.8.0+0
   Installed HistoricalStdlibVersions ─ v1.2.4
   Installed ghr_jll ────────────────── v0.14.0+0
   Installed Gzip_jll ───────────────── v1.13.0+0
   Installed PkgLicenses ────────────── v0.2.0
   Installed ZeroMQ_jll ─────────────── v4.3.5+0
   Installed ObjectFile ─────────────── v0.4.1
   Installed libsodium_jll ──────────── v1.0.20+0
   Installed ExprTools ──────────────── v0.1.10
   Installed TextWrap ───────────────── v1.0.2
   Installed GitHub ─────────────────── v5.9.0
   Installed StructTypes ────────────── v1.10.0
   Installed ArgParse ───────────────── v1.2.0
   Installed unzip_jll ──────────────── v6.0.2+0
   Installed Registrator ────────────── v1.9.3
   Installed OutputCollectors ───────── v0.1.1
  Downloaded artifact: Zstd
  Downloaded artifact: Bzip2
    Downloaded artifact: XZ
  Downloaded artifact: tzjdata
  Downloaded artifact: pigz
   Downloaded artifact: ghr
   Downloaded artifact: Gzip
   Downloaded artifact: Tar
  Downloaded artifact: ZeroMQ
  Downloaded artifact: libsodium
  Downloaded artifact: unzip
    Updating `/private/var/folders/v_/fhpj9jn151d4p9c2fdw2gv780000gn/T/jl_3EAYtE/Project.toml`
  [12aac903] + BinaryBuilder v0.5.8
    Updating `/private/var/folders/v_/fhpj9jn151d4p9c2fdw2gv780000gn/T/jl_3EAYtE/Manifest.toml`
  [c7e460c6] + ArgParse v1.2.0
  [bf4720bc] + AssetRegistry v0.1.0
⌅ [15f4f7f2] + AutoHashEquals v0.2.0
  [12aac903] + BinaryBuilder v0.5.8
  [7f725544] + BinaryBuilderBase v1.30.0
  [d1d4a3ce] + BitFlags v0.1.9
  [944b1d66] + CodecZlib v0.7.4
  [34da2185] + Compat v4.15.0
  [f0e56b4a] + ConcurrentUtilities v2.4.1
  [9a962f9c] + DataAPI v1.16.0
  [e2d170a0] + DataValueInterfaces v1.0.0
  [460bff9d] + ExceptionUnwrapping v0.1.10
  [e2ba6199] + ExprTools v0.1.10
  [5789e2e9] + FileIO v1.16.3
  [8f6bce27] + GitForge v0.4.2
  [bc5e4493] + GitHub v5.9.0
  [cd3eb016] + HTTP v1.10.8
  [9fb69e20] + Hiccup v0.2.2
⌅ [6df8b67a] + HistoricalStdlibVersions v1.2.4
  [842dd82b] + InlineStrings v1.4.1
  [82899510] + IteratorInterfaceExtensions v1.0.0
  [033835bb] + JLD2 v0.4.48
  [692b3bcd] + JLLWrappers v1.5.0
  [682c06a0] + JSON v0.21.4
  [0f8b85d8] + JSON3 v1.14.0
  [e6f89c97] + LoggingExtras v1.0.3
  [1914dd2f] + MacroTools v0.5.13
  [739be429] + MbedTLS v1.1.9
  [78c3b35d] + Mocking v0.7.8
  [ffc61752] + Mustache v1.0.19
  [a975b10e] + Mux v1.0.2
  [d8793406] + ObjectFile v0.4.1
  [4d8831e6] + OpenSSL v1.4.3
  [bac558e1] + OrderedCollections v1.6.3
  [6c11c7d4] + OutputCollectors v0.1.1
  [69de0a69] + Parsers v2.8.1
  [fa939f87] + Pidfile v1.3.0
  [fc669557] + PkgLicenses v0.2.0
  [aea7be01] + PrecompileTools v1.2.1
  [21216c6a] + Preferences v1.4.3
  [92933f4c] + ProgressMeter v1.10.0
  [189a3867] + Reexport v1.2.2
  [4418983a] + Registrator v1.9.3
  [d1eb7eb1] + RegistryTools v2.3.0
  [ae029012] + Requires v1.3.0
  [6c6a2e73] + Scratch v1.2.1
  [777ac1f9] + SimpleBufferStream v1.1.0
  [2133526b] + SodiumSeal v0.1.1
  [53d494c1] + StructIO v0.3.0
  [856f2bd8] + StructTypes v1.10.0
  [dc5dba14] + TZJData v1.2.0+2024a
  [3783bdb8] + TableTraits v1.0.1
  [bd369af6] + Tables v1.11.1
  [b718987f] + TextWrap v1.0.2
  [37f0c46e] + TimeToLive v0.3.0
  [f269a46b] + TimeZones v1.17.0
  [3bb67fe8] + TranscodingStreams v0.10.10
  [5c2747f8] + URIs v1.5.1
  [c2297ded] + ZMQ v1.2.6
  [1fd713ca] + Attr_jll v2.5.2+0
  [6e34b625] + Bzip2_jll v1.0.8+1
  [be1be57a] + Gzip_jll v1.13.0+0
  [94ce4f54] + Libiconv_jll v1.17.0+0
  [458c3c95] + OpenSSL_jll v3.0.14+0
  [9b64493d] + Tar_jll v1.35.0+0
  [ffd25f8a] + XZ_jll v5.4.6+0
  [8f1865be] + ZeroMQ_jll v4.3.5+0
  [3161d3a3] + Zstd_jll v1.5.6+0
⌅ [07c12ed4] + ghr_jll v0.14.0+0
  [a9144af2] + libsodium_jll v1.0.20+0
  [1bc43ea1] + pigz_jll v2.8.0+0
  [88f77b66] + unzip_jll v6.0.2+0
  [0dad84c5] + ArgTools v1.1.1
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8ba89e20] + Distributed
  [f43a241f] + Downloads v1.6.0
  [7b1f6079] + FileWatching
  [b77e0a4c] + InteractiveUtils
  [b27032c2] + LibCURL v0.6.4
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [ca575930] + NetworkOptions v1.2.0
  [44cfe95a] + Pkg v1.10.0
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA v0.7.0
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [fa267f1f] + TOML v1.0.3
  [a4e569a6] + Tar v1.10.0
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [e66e0078] + CompilerSupportLibraries_jll v1.1.1+0
  [deac9b47] + LibCURL_jll v8.4.0+0
  [e37daf67] + LibGit2_jll v1.6.4+0
  [29816b5a] + LibSSH2_jll v1.11.0+1
  [c8ffd9c3] + MbedTLS_jll v2.28.2+1
  [14a3606d] + MozillaCACerts_jll v2023.1.10
  [4536629a] + OpenBLAS_jll v0.3.23+4
  [83775a58] + Zlib_jll v1.2.13+1
  [8e850b90] + libblastrampoline_jll v5.8.0+1
  [8e850ede] + nghttp2_jll v1.52.0+1
  [3f19e933] + p7zip_jll v17.4.0+2
julia> using BinaryBuilder

julia> BinaryBuilder.run_wizard()

    o      `.
   o*o      \'-_               00000000: 01111111  .
     \\      \;"".     ,;.--*  00000001: 01000101  E
      \\     ,\''--.--'/       00000002: 01001100  L
      :=\--<' `""  _   |       00000003: 01000110  F
      ||\\     `" / ''--       00000004: 00000010  .
      `/_\\,-|    |            00000005: 00000001  .
          \\/     L
           \\ ,'   \
         _/ L'   `  \          Join us in the #binarybuilder channel on the
        /  /    /   /          community slack: https://julialang.org/slack/
       /  /    |    \
      "_''--_-''---__=;        https://github.com/JuliaPackaging/BinaryBuilder.jl

Welcome to the BinaryBuilder wizard.  We'll get you set up in no time.

			# Step 1: Select your platforms

Make a platform selection
 > All Supported Platforms
   Select by Operating System
   Fully Custom Platform Choice

Apple restricts distribution and usage of the macOS SDK, a necessary
component to build software for macOS targets.  Please read the Apple
and Xcode SDK agreement for more information on the restrictions and
legal terms you agree to when using the SDK to build software for Apple
operating systems: https://images.apple.com/legal/sla/docs/xcode.pdf.
Would you like to download and use the macOS SDK? [y/N]: y

			# Step 2a: Obtain the source code

Please enter a URL (git repository or compressed archive) containing the source code to build or `N` to stop:
> https://github.com/ekzhang/bore

The entered URL has been canonicalized to
https://github.com/ekzhang/bore.git

┌ Info: Cloning git repository
│   url = "https://github.com/ekzhang/bore.git"
└   repo_path = "/Users/fons/.julia/packages/BinaryBuilderBase/JOwzH/deps/downloads/clones/bore.git-2aafe3046af86eef5dfd82ef129cc86f46b6dedde37eb76e3d6f7150cacf6d36"
You have selected a git repository. Please enter a branch, commit or tag to use.
Please note that for reproducibility, the exact commit will be recorded, 
so updates to the remote resource will not be used automatically; 
you will have to manually update the recorded commit.
> v0.5.1

Recorded as 882ce047e66b50b0e840ee7571d899104af53123

Would you like to download additional sources?  [y/N]: y
Please enter a URL (git repository or compressed archive) containing the source code to build or `N` to stop:
> N

Would you like to download additional sources?  [y/N]: 

			# Step 2b: Obtain binary dependencies (if any)

Do you require any (binary) dependencies?  [y/N]: 

[ Info: Cloning bare Yggdrasil into deps/Yggdrasil...
Enter a name for this project.  This will be used for filenames:
> bore

Enter a version number for this project:
> 0.5.1

Do you want to customize the set of compilers? [y/N]: y
Select compilers for the project
[press: Enter=toggle, a=all, n=none, d=done, q=abort]
   [X] C/C++/Fortran
   [ ] Go
 > [X] Rust
Select the preferred GCC version (default: 4.8.5)
 > 4.8.5
   5.2.0
   6.1.0
   7.1.0
   8.1.0
   9.1.0
   10.2.0
   11.1.0
   12.1.0
v  13.2.0
Select the preferred LLVM version (default: 16.0.6)
 > 16.0.6
   13.0.1
   12.0.0
   11.0.1
   9.0.1
   8.0.1
   7.1.0
   6.0.1
			# Step 3: Build for Linux x86_64 {libc=glibc}

You will now be dropped into the cross-compilation environment.
Please compile the package. Your initial compilation target is x86_64-linux-gnu
The $prefix environment variable contains the target directory.
Once you are done, exit by typing `exit` or `^D`

You have the following contents in your working directory:
  - bore

     Failure artifact: Rootfs.v2024.3.29.x86_64-linux-musl.unpacked
 Downloading artifact: Rootfs.v2024.3.29.x86_64-linux-musl.unpacked
[ Info: No hash cache found
[ Info: Calculated hash f51e2d7defe0979abff04e024f75d75d1ef18da9cc9813dbfd5deb8701b8cf7f for file /var/folders/v_/fhpj9jn151d4p9c2fdw2gv780000gn/T/jl_zQjmTGt8Tg-download.gz
[ Info: Unpacking /var/folders/v_/fhpj9jn151d4p9c2fdw2gv780000gn/T/jl_zQjmTGt8Tg  Downloaded artifact: Rootfs.v2024.3.29.x86_64-linux-musl.unpacked
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
tar: Write error
failed processes:
  Process(`tar -c --no-xattrs -C /Users/fons/.julia/artifacts/73b10e7f9f6b94c9754056030a3adbcf64bf5b90 .`, ProcessExited(1)) [1]
  Process(`docker import - -c 'ENTRYPOINT ["/docker_entrypoint.sh"]' julia_binarybuilder_rootfs:v2024.3.29-bf5b90`, ProcessExited(1)) [1]

Stacktrace:
  [1] pipeline_error(procs::Base.ProcessChain)
    @ Base ./process.jl:578
  [2] run(::Base.CmdRedirect; wait::Bool)
    @ Base ./process.jl:480
  [3] run
    @ ./process.jl:477 [inlined]
  [4] import_docker_image(rootfs::BinaryBuilderBase.CompilerShard, workspace_root::String; verbose::Bool)
    @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/JOwzH/src/DockerRunner.jl:56
  [5] import_docker_image
    @ ~/.julia/packages/BinaryBuilderBase/JOwzH/src/DockerRunner.jl:40 [inlined]
  [6] BinaryBuilderBase.DockerRunner(workspace_root::String; cwd::String, platform::Platform, workspaces::Vector{Pair{String, String}}, extra_env::Dict{String, String}, verbose::Bool, compiler_wrapper_path::String, toolchains_path::String, src_name::String, shards::Nothing, kwargs::@Kwargs{compilers::Vector{Symbol}, preferred_gcc_version::VersionNumber, preferred_llvm_version::VersionNumber})
    @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/JOwzH/src/DockerRunner.jl:90
  [7] step34(state::BinaryBuilder.Wizard.WizardState)
    @ BinaryBuilder.Wizard ~/.julia/packages/BinaryBuilder/L8tBh/src/wizard/interactive_build.jl:534
  [8] run_wizard(state::Nothing)
    @ BinaryBuilder.Wizard ~/.julia/packages/BinaryBuilder/L8tBh/src/Wizard.jl:104
  [9] run_wizard()
    @ BinaryBuilder.Wizard ~/.julia/packages/BinaryBuilder/L8tBh/src/Wizard.jl:87
 [10] top-level scope
    @ REPL[6]:1
 [11] eval
    @ ./boot.jl:385 [inlined]
 [12] eval_user_input(ast::Any, backend::REPL.REPLBackend, mod::Module)
    @ REPL /Applications/Julia-1.10 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:150
 [13] repl_backend_loop(backend::REPL.REPLBackend, get_module::Function)
    @ REPL /Applications/Julia-1.10 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:246
 [14] start_repl_backend(backend::REPL.REPLBackend, consumer::Any; get_module::Function)
    @ REPL /Applications/Julia-1.10 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:231
 [15] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool, backend::Any)
    @ REPL /Applications/Julia-1.10 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:389
 [16] run_repl(repl::REPL.AbstractREPL, consumer::Any)
    @ REPL /Applications/Julia-1.10 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:375
 [17] (::Base.var"#1013#1015"{Bool, Bool, Bool})(REPL::Module)
    @ Base ./client.jl:432
 [18] #invokelatest#2
    @ ./essentials.jl:892 [inlined]
 [19] invokelatest
    @ ./essentials.jl:889 [inlined]
 [20] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
    @ Base ./client.jl:416
 [21] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:333
 [22] _start()
    @ Base ./client.jl:552

WizardState [step3]

julia> # (here i started docker)

julia> BinaryBuilder.run_wizard()
Would you like to resume the previous incomplete wizard run?
 > Resume previous run
   Start from scratch
			# Step 3: Build for Linux x86_64 {libc=glibc}

You will now be dropped into the cross-compilation environment.
Please compile the package. Your initial compilation target is x86_64-linux-gnu
The $prefix environment variable contains the target directory.
Once you are done, exit by typing `exit` or `^D`

You have the following contents in your working directory:
  - bore

 Downloading artifact: PlatformSupport-x86_64-linux-gnu.v2023.6.10.x86_64-linux-musl.unpacked
  Downloaded artifact: PlatformSupport-x86_64-linux-gnu.v2023.6.10.x86_64-linux-musl.unpacked
 Downloading artifact: GCCBootstrap-x86_64-linux-gnu.v4.8.5.x86_64-linux-musl.unpacked
     Failure artifact: GCCBootstrap-x86_64-linux-gnu.v4.8.5.x86_64-linux-musl.unpacked
 Downloading artifact: GCCBootstrap-x86_64-linux-gnu.v4.8.5.x86_64-linux-musl.unpacked
[ Info: No hash cache found
[ Info: Calculated hash 1250fe46ddf2c897321891b02f3dd60e466090397b92085dea90dc939dbbb8ed for file /var/folders/v_/fhpj9jn151d4p9c2fdw2gv780000gn/T/jl_Zw5Ct6ZUxs-download.gz
     Failure artifact: GCCBootstrap-x86_64-linux-gnu.v4.8.5.x86_64-linux-musl.unpacked
Unable to automatically download/install artifact 'GCCBootstrap-x86_64-linux-gnu.v4.8.5.x86_64-linux-musl.unpacked' from sources listed in '/Users/fons/.julia/packages/BinaryBuilderBase/JOwzH/Artifacts.toml'.
Sources attempted:
- https://pkg.julialang.org/artifact/305c8b171016c46dfbb8ca234a543a99b6e3d045
    Error: AssertionError: size == padded_size == 0
- https://github.com/JuliaPackaging/Yggdrasil/releases/download/GCCBootstrap-v4.8.5+1/GCCBootstrap-x86_64-linux-gnu.v4.8.5.x86_64-linux-musl.unpacked.tar.gz
    Error: AssertionError: size == padded_size == 0

Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] ensure_artifact_installed(name::String, meta::Dict{String, Any}, artifacts_toml::String; platform::Platform, verbose::Bool, quiet_download::Bool, io::Base.TTY)
    @ Pkg.Artifacts /Applications/Julia-1.10 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Artifacts.jl:467
  [3] ensure_artifact_installed(name::String, artifacts_toml::String; platform::Platform, pkg_uuid::Nothing, verbose::Bool, quiet_download::Bool, io::Base.TTY)
    @ Pkg.Artifacts /Applications/Julia-1.10 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Artifacts.jl:403
  [4] mount(cs::BinaryBuilderBase.CompilerShard, build_prefix::String; verbose::Bool)
    @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/JOwzH/src/Rootfs.jl:260
  [5] mount
    @ ~/.julia/packages/BinaryBuilderBase/JOwzH/src/Rootfs.jl:231 [inlined]
  [6] #43
    @ ./broadcast.jl:1327 [inlined]
  [7] _broadcast_getindex_evalf
    @ ./broadcast.jl:709 [inlined]
  [8] _broadcast_getindex
    @ ./broadcast.jl:682 [inlined]
  [9] getindex
    @ ./broadcast.jl:636 [inlined]
 [10] macro expansion
    @ ./broadcast.jl:1004 [inlined]
 [11] macro expansion
    @ ./simdloop.jl:77 [inlined]
 [12] copyto!
    @ ./broadcast.jl:1003 [inlined]
 [13] copyto!
    @ ./broadcast.jl:956 [inlined]
 [14] copy
    @ ./broadcast.jl:928 [inlined]
 [15] materialize
    @ ./broadcast.jl:903 [inlined]
 [16] mount_shards(ur::BinaryBuilderBase.DockerRunner; verbose::Bool)
    @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/JOwzH/src/Rootfs.jl:1085
 [17] mount_shards
    @ ~/.julia/packages/BinaryBuilderBase/JOwzH/src/Rootfs.jl:1084 [inlined]
 [18] run_interactive(dr::BinaryBuilderBase.DockerRunner, cmd::Cmd; stdin::Base.TTY, stdout::Base.TTY, stderr::Base.TTY, verbose::Bool)
    @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/JOwzH/src/DockerRunner.jl:215
 [19] interactive_build(state::BinaryBuilder.Wizard.WizardState, prefix::Prefix, ur::BinaryBuilderBase.DockerRunner, build_path::String, platform::Platform; prefix_artifacts::Dict{Prefix, Vector{String}}, hist_modify::typeof(string), srcdir_overlay::Bool)
    @ BinaryBuilder.Wizard ~/.julia/packages/BinaryBuilder/L8tBh/src/wizard/interactive_build.jl:335
 [20] interactive_build
    @ ~/.julia/packages/BinaryBuilder/L8tBh/src/wizard/interactive_build.jl:309 [inlined]
 [21] step3_interactive(state::BinaryBuilder.Wizard.WizardState, prefix::Prefix, platform::Platform, ur::BinaryBuilderBase.DockerRunner, build_path::String, artifact_paths::Vector{String})
    @ BinaryBuilder.Wizard ~/.julia/packages/BinaryBuilder/L8tBh/src/wizard/interactive_build.jl:415
 [22] step34(state::BinaryBuilder.Wizard.WizardState)
    @ BinaryBuilder.Wizard ~/.julia/packages/BinaryBuilder/L8tBh/src/wizard/interactive_build.jl:546
 [23] run_wizard(state::Nothing)
    @ BinaryBuilder.Wizard ~/.julia/packages/BinaryBuilder/L8tBh/src/Wizard.jl:104
 [24] run_wizard()
    @ BinaryBuilder.Wizard ~/.julia/packages/BinaryBuilder/L8tBh/src/Wizard.jl:87
 [25] top-level scope
    @ REPL[6]:1
 [26] eval
    @ ./boot.jl:385 [inlined]
 [27] eval_user_input(ast::Any, backend::REPL.REPLBackend, mod::Module)
    @ REPL /Applications/Julia-1.10 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:150
 [28] repl_backend_loop(backend::REPL.REPLBackend, get_module::Function)
    @ REPL /Applications/Julia-1.10 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:246
 [29] start_repl_backend(backend::REPL.REPLBackend, consumer::Any; get_module::Function)
    @ REPL /Applications/Julia-1.10 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:231
 [30] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool, backend::Any)
    @ REPL /Applications/Julia-1.10 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:389
 [31] run_repl(repl::REPL.AbstractREPL, consumer::Any)
    @ REPL /Applications/Julia-1.10 ARM.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:375
 [32] (::Base.var"#1013#1015"{Bool, Bool, Bool})(REPL::Module)
    @ Base ./client.jl:432
 [33] #invokelatest#2
    @ ./essentials.jl:892 [inlined]
 [34] invokelatest
    @ ./essentials.jl:889 [inlined]
 [35] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
    @ Base ./client.jl:416
 [36] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:333
 [37] _start()
    @ Base ./client.jl:552

WizardState [step3]

julia> 
```

**Comment by giordano** [comment] 2024-07-01 14:10
Unfortunately BinaryBuilder doesn't really work on Windows, see for example #25 (note the 2-digit issue number), and #1246.  I'm closing this ticket as duplicate of those issues.

**Closed by giordano** 2024-07-01 14:10 UTC
Labels: windows :window:
