### ISSUE TITLE
Cannot install BinaryBuilder on Julia 1.7

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/BinaryBuilder.jl#1130] opened 2021-12-17 14:59 UTC
This fails:
```
(@v1.7) pkg> add BinaryBuilder
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package BinaryBuilder [12aac903]:
 BinaryBuilder [12aac903] log:
 ├─possible versions are: 0.1.0-0.4.4 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.4.4
 ├─restricted by julia compatibility requirements to versions: 0.3.0-0.4.4 or uninstalled, leaving only versions: 0.3.0-0.4.4
 └─restricted by compatibility requirements with BinaryBuilderBase [7f725544] to versions: 0.1.0-0.2.5 or uninstalled — no versions left
   └─BinaryBuilderBase [7f725544] log:
     ├─possible versions are: 0.1.0-1.2.0 or uninstalled
     └─restricted by julia compatibility requirements to versions: uninstalled
```

(This is macOS Monterey 12.1.)

However, the release notes imply that Julia 1.7 should be supported.

**Comment by giordano** [comment] 2021-12-17 15:02
Duplicate of https://github.com/JuliaPackaging/BinaryBuilderBase.jl/issues/170.

I've been trying to fix it since last March in https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/129, but ran into too many different issues and never got around them.

**Closed by giordano** 2021-12-17 15:02 UTC
