### ISSUE TITLE
macos fails hash check

### ISSUE THREAD

**Issue by jstrube** [JuliaPackaging/BinaryBuilder.jl#593] opened 2019-12-31 22:55 UTC
When trying to build a binary on MacOS, BB fails to install the environment with the following error:
```
[ Info: Downloading https://github.com/JuliaPackaging/Yggdrasil/releases/download/PlatformSupport-v2019.12.20+0/PlatformSupport-x86_64-apple-darwin14.v2019.12.20.x86_64-linux-musl.unpacked.tar.gz to /tmp/jl_v1E5Bj-download.gz...
######################################################################## 100.0%
[ Info: No hash cache found
[ Info: Calculated hash a40a3d3f198d5345d789e371a929714f77c062eb202ba677d5eb46091ec4f092 for file /tmp/jl_v1E5Bj-download.gz
[ Info: Unpacking /tmp/jl_v1E5Bj-download.gz into /home/jstrube/.julia/artifacts/jl_nEtsIi...
┌ Error: Tree Hash Mismatch!
│   Expected git-tree-sha1:   3616cf914f5072a044bf163aa950727001b443ba
│   Calculated git-tree-sha1: ea0705297868652a337daf0ccf6d6278796b5ed6
└ @ Pkg.Artifacts /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Pkg/src/Artifacts.jl:779
Unable to automatically install 'PlatformSupport-x86_64-apple-darwin14.v2019.12.20.x86_64-linux-musl.unpacked' from '/home/jstrube/.julia/packages/BinaryBuilder/oKsbb/Artifacts.toml'                                                                                                                                                          
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] #ensure_artifact_installed#42(::Platform, ::Bool, ::typeof(Pkg.Artifacts.ensure_artifact_installed), ::String, ::Dict{String,Any}, ::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Pkg/src/Artifacts.jl:873
 [3] (::Pkg.Artifacts.var"#kw##ensure_artifact_installed")(::NamedTuple{(:platform, :verbose),Tuple{Linux,Bool}}, ::typeof(Pkg.Artifacts.ensure_artifact_installed), ::String, ::Dict{String,Any}, ::String) at ./none:0
 [4] #ensure_artifact_installed#41(::Platform, ::Nothing, ::Bool, ::typeof(Pkg.Artifacts.ensure_artifact_installed), ::String, ::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Pkg/src/Artifacts.jl:849
 [5] (::Pkg.Artifacts.var"#kw##ensure_artifact_installed")(::NamedTuple{(:platform, :verbose),Tuple{Linux,Bool}}, ::typeof(Pkg.Artifacts.ensure_artifact_installed), ::String, ::String) at ./none:0
 [6] #mount#217(::Bool, ::typeof(BinaryBuilder.mount), ::BinaryBuilder.CompilerShard, ::String) at /home/jstrube/.julia/packages/BinaryBuilder/oKsbb/src/Rootfs.jl:218
 [7] #mount at ./none:0 [inlined]
 [8] #31 at ./broadcast.jl:1219 [inlined]
 [9] _broadcast_getindex_evalf at ./broadcast.jl:630 [inlined]
 [10] _broadcast_getindex at ./broadcast.jl:603 [inlined]
 [11] getindex at ./broadcast.jl:563 [inlined]
 [12] macro expansion at ./broadcast.jl:909 [inlined]
 [13] macro expansion at ./simdloop.jl:77 [inlined]
 [14] copyto! at ./broadcast.jl:908 [inlined]
 [15] copyto! at ./broadcast.jl:863 [inlined]
 [16] copy(::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},Base.Broadcast.var"#31#32"{Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:verbose,),Tuple{Bool}}},typeof(BinaryBuilder.mount)},Tuple{Array{BinaryBuilder.CompilerShard,1},Base.RefValue{String}}}) at ./broadcast.jl:839
 [17] materialize at ./broadcast.jl:819 [inlined]
 [18] #mount_shards#240 at /home/jstrube/.julia/packages/BinaryBuilder/oKsbb/src/Rootfs.jl:599 [inlined]
 [19] #mount_shards at ./none:0 [inlined]
 [20] #run_interactive#251(::Base.TTY, ::Base.TTY, ::Base.TTY, ::Bool, ::typeof(BinaryBuilder.run_interactive), ::BinaryBuilder.UserNSRunner, ::Cmd) at /home/jstrube/.julia/packages/BinaryBuilder/oKsbb/src/UserNSRunner.jl:180
 [21] #run_interactive at ./none:0 [inlined]
 [22] #runshell#213 at /home/jstrube/.julia/packages/BinaryBuilder/oKsbb/src/Runner.jl:633 [inlined]
 [23] (::BinaryBuilder.var"#kw##runshell")(::NamedTuple{(:stdin, :stdout, :stderr),Tuple{Base.TTY,Base.TTY,Base.TTY}}, ::typeof(BinaryBuilder.runshell), ::BinaryBuilder.UserNSRunner) at ./none:0
 [24] #interactive_build#438(::typeof(string), ::typeof(BinaryBuilder.interactive_build), ::BinaryBuilder.WizardState, ::Prefix, ::BinaryBuilder.UserNSRunner, ::String) at /home/jstrube/.julia/packages/BinaryBuilder/oKsbb/src/wizard/interactive_build.jl:141
 [25] interactive_build at /home/jstrube/.julia/packages/BinaryBuilder/oKsbb/src/wizard/interactive_build.jl:140 [inlined]
 [26] step3_interactive(::BinaryBuilder.WizardState, ::Prefix, ::MacOS, ::BinaryBuilder.UserNSRunner, ::String, ::Array{String,1}) at /home/jstrube/.julia/packages/BinaryBuilder/oKsbb/src/wizard/interactive_build.jl:190
 [27] step34(::BinaryBuilder.WizardState) at /home/jstrube/.julia/packages/BinaryBuilder/oKsbb/src/wizard/interactive_build.jl:313
 [28] run_wizard(::Nothing) at /home/jstrube/.julia/packages/BinaryBuilder/oKsbb/src/Wizard.jl:92
 [29] run_wizard() at /home/jstrube/.julia/packages/BinaryBuilder/oKsbb/src/Wizard.jl:75
 [30] top-level scope at REPL[2]:1
 [31] eval(::Module, ::Any) at ./boot.jl:330
 [32] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:86
 [33] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:118 [inlined]
 [34] (::REPL.var"#26#27"{REPL.REPLBackend})() at ./task.jl:333
```

**Comment by giordano** [comment] 2020-01-01 00:04
Julia and BinaryBuilder.jl versions? What's your umask? Did you try to redownload?

**Comment by jstrube** [comment] 2020-01-01 00:05
julia-1.3.1, BB 0.2.1, umask 0002, I tried downloading multiple times.

**Comment by giordano** [comment] 2020-01-01 00:09
What happens if you temporarily set the umask to 022?

**Comment by jstrube** [comment] 2020-01-01 00:12
same error

**Comment by giordano** [comment] 2020-01-02 12:23
For the record, this is also making test fail on Travis: https://travis-ci.org/JuliaPackaging/BinaryBuilder.jl/jobs/631650974

**Comment by staticfloat** [comment] 2020-01-02 19:32
What filesystem are you installing on?  I've tried on two different computers and they both calculate the correct hash. :/

**Comment by giordano** [comment] 2020-01-02 19:38
XFS, there is a thread on slack

**Comment by jstrube** [comment] 2020-01-02 20:22
actually, xfs was the local dir.
~/.julia and /tmp are mounted on `/dev/sda2 on / type ext4 (rw,relatime,errors=remount-ro)`

**Comment by giordano** [comment] 2020-01-02 22:04
@staticfloat can you reproduce with `BINARYBUILDER_RUNNER=docker`?  The Travis job is failing, giving the same hash found by @jstrube.

**Comment by staticfloat** [comment] 2020-01-02 22:09
No, but there's a more direct test.  Just download and extract the tarball, then ask Julia to hash it for you:

```
$ mkdir /tmp/foo && cd /tmp/foo
$ curl -L 'https://github.com/JuliaPackaging/Yggdrasil/releases/download/PlatformSupport-v2019.12.20+0/PlatformSupport-x86_64-apple-darwin14.v2019.12.20.x86_64-linux-musl.unpacked.tar.gz' | tar zx
$ julia -e 'import Pkg; println(bytes2hex(Pkg.GitTools.tree_hash(".")))'
3616cf914f5072a044bf163aa950727001b443ba
```

If you do that, do you get a different answer?

**Comment by jstrube** [comment] 2020-01-02 22:10
I get `ea0705297868652a337daf0ccf6d6278796b5ed6`

**Comment by staticfloat** [comment] 2020-01-02 22:36
Aha!  I found it.  It's because of empty directories.  That hashing behavior changed in 1.3.1.

**Comment by giordano** [comment] 2020-01-02 22:41
The [other Travis jobs](https://travis-ci.org/JuliaPackaging/BinaryBuilder.jl/builds/631650970) are passing because of caching?

**Comment by staticfloat** [comment] 2020-01-02 22:42
Probably because they use `squashfs` shards instead of `unpacked` ones.

**Comment by giordano** [comment] 2020-01-02 22:44
Oh, different artifact

**Comment by staticfloat** [comment] 2020-01-03 00:02
Okay so this is a bug in 1.3.1 that will be fixed in 1.3.2.  For now, you should probably stick with 1.3.0, or use BB on Linux, unfortunately.  The relevant issue is https://github.com/JuliaLang/Pkg.jl/pull/1581

**Comment by jstrube** [comment] 2020-01-03 00:43
Thanks for tracking this down. Not sure I understand that last comment, though. I _am_ on Linux... I've tried to build _for_ MacOS. Is that what you meant?

**Comment by staticfloat** [comment] 2020-01-03 00:48
Ah, sorry, I thought you were on MacOS (where this issue will also manifest).

Are you able to use squashfs images?  You can try by exporting `BINARYBUILDER_USE_SQUASHFS=true` before starting Julia.

**Comment by jstrube** [comment] 2020-01-03 01:46
Seems to work with squashfs on Julia-1.3.1.

**Comment by staticfloat** [comment] 2020-01-03 21:53
Fantastic; we'll use that workaround for now until we get Julia 1.3.2 pushed out with an appropriate fix.

**Comment by giordano** [comment] 2020-01-06 16:02
Should we run tests on Julia 1.3.0 until this is sorted out?  This is making tests with `BINARYBUILDER_USE_SQUASHFS=true` useless (and marking all tests as failing)

**Comment by fingolfin** [comment] 2020-11-06 01:28
Can this be closed now?

**Closed** 2020-11-06 01:31 UTC
