### ISSUE TITLE
Dependency issues preventing installation on Apple Silicon macs (Julia v1.7)

### ISSUE THREAD

**Issue by truedichotomy** [JuliaPackaging/BinaryBuilder.jl#1120] opened 2021-12-02 07:26 UTC
When I try to install BinaryBuilder on a M1 mac running Julia v1.7, I get the follow error:

```
(@ocean) pkg> add BinaryBuilder
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package BinaryBuilderBase [7f725544]:
 BinaryBuilderBase [7f725544] log:
 ├─possible versions are: 0.1.0-1.0.4 or uninstalled
 ├─restricted by julia compatibility requirements to versions: uninstalled
 └─restricted by compatibility requirements with BinaryBuilder [12aac903] to versions: [0.5.0-0.5.4, 0.6.1-1.0.4] — no versions left
   └─BinaryBuilder [12aac903] log:
     ├─possible versions are: 0.1.0-0.4.2 or uninstalled
     ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.4.2
     └─restricted by julia compatibility requirements to versions: 0.3.0-0.4.2 or uninstalled, leaving only versions: 0.3.0-0.4.2
```

**Comment by giordano** [comment] 2021-12-02 09:16
Yes, this is on purpose: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/blob/fb9317549d0247d7c18b6a27594fd74c39c26427/Project.toml#L33

Duplicate of https://github.com/JuliaPackaging/BinaryBuilderBase.jl/issues/170

**Closed by giordano** 2021-12-02 09:16 UTC
